apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: internal
  name: typesense
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 1
      containers:
      - args:
        - --data-dir=/tmp/typesense
        - --api-key=blnk-api-key
        - --listen-port=8108
        image: typesense/typesense:0.23.1
        ports:
        - containerPort: 8108
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8108
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 8108
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 10
      serviceAccountName: 438091062981-compute@developer.gserviceaccount.com
      timeoutSeconds: 600
  traffic:
  - latestRevision: true
    percent: 100
